<a href="https://colab.research.google.com/github/NguyenthanhTung14/Nguy-nThanhT-ng/blob/main/Ngay_20_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from sklearn.linear_model import Perceptron
x=[[0,0],[0,1],[1,0],[1,1]]#cot
t= [0,1,1,1] #hang
model = Perceptron()
model.fit(x,t)
model.score(x,t)


1.0

In [9]:
x1=[[0.5,-1],[0.5,0.5],[-10,1]]
y1=model.predict(x1)

In [10]:
model.score(x1,y1)

1.0

In [14]:

x3=[[-0.5,1],[-0.5,1],[0.3,0],[-0.1,0]]
y3=model.predict(x3)
model.score(x3,y3)


1.0

In [24]:
import  numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [40]:
X= iris.data
y=iris.target
print(X[:5])
print(y[:5])
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.3)
sc=StandardScaler()
sc.fit(X_train)
X_train_std=sc.transform(X_train)
X_test_std=sc.transform(X_test)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [41]:
model= Perceptron(max_iter= 40,eta0=0.1,random_state=0)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('Độ chính xác của mô hình: ', accuracy_score(y_test,y_pred))

[1 2 1 2 0 0 0 2 2 2 2 0 1 0 2 1 0 1 1 1 1 2 2 0 0 2 2 2 0 2 0 1 2 2 1 0 2
 2 0 0 1 2 1 0 0]
[1 2 1 2 0 0 0 2 2 2 2 0 1 0 2 1 0 1 1 1 1 2 1 0 0 1 1 2 0 1 0 0 2 2 1 0 2
 2 0 1 1 2 1 0 0]
Độ chính xác của mô hình:  0.8666666666666667


ValueError: ignored